"""Generated by aptprep deb_package_repo. DO NOT EDIT."""

exports_files([
    "{DEB_FILENAME}",
    "{DATA_ARCHIVE_FILENAME}",
    "{DATA_ARCHIVE_METADATA_FILENAME}",
    "{CONTROL_ARCHIVE_FILENAME}",
])

alias(
    name = "file",
    actual = ":{DEB_FILENAME}",
    visibility = ["//visibility:public"],
)

alias(
    name = "data",
    actual = ":{DATA_ARCHIVE_FILENAME}",
    visibility = ["//visibility:public"],
)

alias(
    name = "control",
    actual = ":{CONTROL_ARCHIVE_FILENAME}",
    visibility = ["//visibility:public"],
)
