"""Generated by aptprep extension. DO NOT EDIT."""

# Alias to the .deb file from http_file (for packages extension)
alias(
    name = "deb",
    actual = "@{REPO_NAME}__{PACKAGE_KEY}//:file",
    visibility = ["//visibility:public"],
)

filegroup(
    name = "{ARCHITECTURE}",
    srcs = [":deb"]{DEPS},
    visibility = ["//visibility:public"],
)
