"""Generated by aptprep extension. DO NOT EDIT."""

alias(
    name = "data",
    actual = "@{REPO_NAME}__{PACKAGE_KEY}//:data",
    visibility = ["//visibility:public"],
)

alias(
    name = "control",
    actual = "@{REPO_NAME}__{PACKAGE_KEY}//:control",
    visibility = ["//visibility:public"],
)

filegroup(
    name = "{ARCHITECTURE}",
    srcs = [":data"]{DEPS},
    visibility = ["//visibility:public"],
)
