"""Generated by aptprep extension. DO NOT EDIT."""

# Aliases to artifacts exposed by deb_file_repo.
alias(
    name = "deb",
    actual = "@{PACKAGE_REPO_PREFIX}__{PACKAGE_KEY}//:file",
    visibility = ["//visibility:public"],
)

alias(
    name = "data",
    actual = "@{PACKAGE_REPO_PREFIX}__{PACKAGE_KEY}//:data",
    visibility = ["//visibility:public"],
)

alias(
    name = "control",
    actual = "@{PACKAGE_REPO_PREFIX}__{PACKAGE_KEY}//:control",
    visibility = ["//visibility:public"],
)

filegroup(
    name = "{ARCHITECTURE}",
    srcs = [":data"]{DEPS},
    visibility = ["//visibility:public"],
)
