"""Package repository rules and helpers for aptprep extension."""

# Template for root repository BUILD file
_ROOT_BUILD_TEMPLATE = """\"\"\"Generated by aptprep extension for {repo_name}.\"\"\"

load("@rules_aptprep//aptprep/private:generate_packages.bzl", "generate_packages_file")

filegroup(
    name = "all_debs",
    srcs = [{all_deb_targets}],
    visibility = ["//visibility:public"],
)

{packages_file_rule}
"""

def _generate_package_substitutions(main_repo_name, package_repo_prefix, package_info, dependencies_info, dependency_blacklist = {}):
    """Generate template substitutions for a package BUILD file (per architecture).

    Args:
        main_repo_name: Name of the main repository
        package_repo_prefix: Prefix of per-package repositories created from lockfile.
        package_info: Dict with package information from lockfile
        dependencies_info: Dict mapping dependency keys to their package info
        dependency_blacklist: Dict mapping package names to lists of packages they should not depend on

    Returns:
        Dict of template substitutions for package.BUILD.tpl
    """
    package_name = package_info["name"]
    architecture = package_info["architecture"]
    dependencies = package_info.get("dependencies", [])

    # Get the blacklist for this package (list of packages it should not depend on)
    blacklisted_deps = dependency_blacklist.get(package_name, [])

    # Generate dependency references using actual package info from lockfile
    dep_refs = []
    for dep_key in dependencies:
        if dep_key in dependencies_info:
            dep_info = dependencies_info[dep_key]
            dep_name = dep_info["name"]

            # Skip if this dependency is blacklisted for this package
            if dep_name in blacklisted_deps:
                continue
            dep_arch = dep_info["architecture"]
            dep_refs.append('\"@{}//{}/{}\"'.format(main_repo_name, dep_name, dep_arch))

    deps_str = " + [\n        " + ",\n        ".join(dep_refs) + ",\n    ]" if dep_refs else ""

    # Use the original package key from the lockfile for the repository reference
    package_key = None
    for key, info in dependencies_info.items():
        if (info["name"] == package_name and
            info["architecture"] == architecture):
            package_key = key
            break

    if not package_key:
        fail("Could not find package key for {}:{}".format(package_name, architecture))

    return {
        "{PACKAGE_REPO_PREFIX}": package_repo_prefix,
        "{PACKAGE_KEY}": package_key,
        "{PACKAGE_NAME}": package_name,
        "{DEPS}": deps_str,
        "{ARCHITECTURE}": architecture,
    }

def _generate_root_build_file(repo_name, packages, lockfile_label = None, config_label = None):
    """Generate root BUILD.bazel file for the main repository.

    Args:
        repo_name: Name of the repository
        packages: Dict of all packages from lockfile
        lockfile_label: Optional label of the lockfile for Packages generation
        config_label: Optional label of the config for Packages generation

    Returns:
        String content for root BUILD.bazel
    """

    # Generate list of all deb targets
    deb_targets = []
    for package_info in packages.values():
        package_name = package_info["name"]
        architecture = package_info["architecture"]
        deb_targets.append('"//{}/{}:deb"'.format(package_name, architecture))

    all_deb_targets = ",\n        ".join(deb_targets)

    # Generate Packages file rule if lockfile is provided
    packages_file_rule = ""
    if lockfile_label:
        config_attr = ""
        if config_label:
            config_attr = '\n    config = "{}",'.format(config_label)

        packages_file_rule = '''generate_packages_file(
    name = "Packages",
    lockfile = "{}",{}
    out = "Packages",
    visibility = ["//visibility:public"],
)'''.format(lockfile_label, config_attr)

    return _ROOT_BUILD_TEMPLATE.format(
        repo_name = repo_name,
        all_deb_targets = all_deb_targets,
        packages_file_rule = packages_file_rule,
    )

def _generate_packages_mapping(packages_dict, package_repo_prefix):
    """Generate a JSON file that maps package names to repository names.

    For packages with multiple versions/architectures, use the package key
    to ensure uniqueness.

    Args:
        packages_dict: Dict of all packages from lockfile
        package_repo_prefix: Prefix of per-package repositories

    Returns:
        String content for the packages_mapping.json file
    """
    return json.encode_indent(_build_packages_mapping(packages_dict, package_repo_prefix))

def _build_packages_mapping(packages_dict, repo_prefix):
    """Build the packages mapping dictionary.

    Args:
        packages_dict: Dict of all packages from lockfile
        repo_prefix: Prefix for repository names

    Returns:
        Dict mapping package names to repository names
    """

    # Group packages by name to detect duplicates
    packages_by_name = {}
    for package_key, package_info in packages_dict.items():
        package_name = package_info["name"]
        if package_name not in packages_by_name:
            packages_by_name[package_name] = []
        packages_by_name[package_name].append((package_key, package_info))

    # Generate mapping dict
    mapping = {}

    for package_name in sorted(packages_by_name.keys()):
        variants = packages_by_name[package_name]

        if len(variants) == 1:
            # Single variant, use simple mapping to repository name
            package_key = variants[0][0]
            repo_ref = "{}_{}".format(repo_prefix, package_key)
            mapping[package_name] = repo_ref
        else:
            # Multiple variants, create a dict with architecture keys
            arch_mapping = {}
            for package_key, package_info in variants:
                arch = package_info["architecture"]
                repo_ref = "{}_{}".format(repo_prefix, package_key)
                arch_mapping[arch] = repo_ref
            mapping[package_name] = arch_mapping

    return mapping

def _aptprep_main_repo_impl(repository_ctx):
    """Implementation for main aptprep repository."""
    repo_name = repository_ctx.attr.repo_name
    package_repo_prefix = repository_ctx.attr.package_repo_prefix
    packages_data = repository_ctx.attr.packages_data
    dependency_blacklist = repository_ctx.attr.dependency_blacklist
    lockfile_label = repository_ctx.attr.lockfile
    config_label = repository_ctx.attr.config

    # Parse packages data (JSON string) using Bazel's json module
    packages = json.decode(packages_data)

    # Create directory structure and BUILD files
    repository_ctx.file(
        "BUILD.bazel",
        _generate_root_build_file(repo_name, packages, lockfile_label, config_label),
    )

    # Generate and write the packages mapping file
    mapping_content = _generate_packages_mapping(packages, package_repo_prefix)
    repository_ctx.file("packages_mapping.json", mapping_content)

    # Generate packages.bzl with PACKAGES dict for use in BUILD files
    packages_bzl_content = "PACKAGES = " + json.encode_indent(packages)
    repository_ctx.file("packages.bzl", packages_bzl_content)

    # Create package directories and BUILD files for each (package_name, architecture) combination
    for package_info in packages.values():
        package_name = package_info["name"]
        architecture = package_info["architecture"]

        substitutions = _generate_package_substitutions(
            repo_name,
            package_repo_prefix,
            package_info,
            packages,  # Pass all packages for dependency resolution
            dependency_blacklist,  # Pass the blacklist
        )

        # Create BUILD file in package/architecture subdirectory using template
        repository_ctx.template(
            "{}/{}/BUILD.bazel".format(package_name, architecture),
            Label("//aptprep/private:package.BUILD.tpl"),
            substitutions = substitutions,
        )

aptprep_main_repo = repository_rule(
    implementation = _aptprep_main_repo_impl,
    attrs = {
        "repo_name": attr.string(mandatory = True),
        "package_repo_prefix": attr.string(mandatory = True, doc = "Prefix of package repositories created from the referenced lockfile."),
        "packages_data": attr.string(mandatory = True),
        "dependency_blacklist": attr.string_list_dict(default = {}, doc = "Dictionary of per-package dependency blacklists. Keys are package names, values are lists of packages they should not depend on."),
        "lockfile": attr.label(mandatory = False, doc = "Label of the lockfile (for generating Packages file)"),
        "config": attr.label(mandatory = False, doc = "Label of the config file (for generating Packages file)"),
    },
)

# Sentinel marker dropped at the root of a fake/ungenerated stand-in repo.
# `cc_toolchain_repo` checks for this file (via `repository_ctx.path(...).exists`)
# to detect that a referenced sysroot has not been generated yet and to switch to
# emitting a STUB cc-toolchain instead of running its real fetch-time validation.
# Exported as a constant so the single source of truth is shared with consumers.
APTPREP_FAKE_SYSROOT_MARKER = "APTPREP_FAKE_SYSROOT"

# A valid-but-empty BUILD for a fake stand-in repo. It must be loadable for BOTH
# the `packages` and `sysroot` roles during bootstrap:
#   * `install_manifest.json` exists so `repository_ctx.path(":install_manifest.json")`
#     resolves for cc_toolchain_repo's sysroot-root detection.
#   * empty `filegroup`s (`:files`, `:all_files`) stand in for the labels a stub
#     cc_toolchain references; `allow_empty` keeps the globs valid with no files.
# A packages stand-in only needs to be a loadable empty repo for bootstrap — we do
# NOT fabricate per-package targets here.
_FAKE_BUILD = """\"\"\"Generated by aptprep extension as an UNGENERATED stand-in for {repo_name}.

This is a fake/empty repository materialized because the lockfile backing
'{repo_name}' has not been generated yet. It exists so that module-extension
evaluation and toolchain resolution can proceed during bootstrap; it contains no
real package or sysroot contents. Generate the relevant aptprep lockfile (e.g.
`./projx sysroot lock`) and rebuild to replace it with the real repository.
\"\"\"

package(default_visibility = ["//visibility:public"])

exports_files(["install_manifest.json", "{marker}"])

filegroup(
    name = "files",
    srcs = glob(["**/*"], allow_empty = True),
    visibility = ["//visibility:public"],
)

filegroup(
    name = "all_files",
    srcs = glob(["**/*"], allow_empty = True),
    visibility = ["//visibility:public"],
)
"""

def _aptprep_fake_repo_impl(repository_ctx):
    repo_name = repository_ctx.attr.repo_name

    # A repository rule that writes nothing makes Bazel fail with
    # "... must create a directory"; materialize a minimal valid repo instead.
    repository_ctx.file(
        "BUILD.bazel",
        _FAKE_BUILD.format(
            repo_name = repo_name,
            marker = APTPREP_FAKE_SYSROOT_MARKER,
        ),
    )

    # Stub manifest so `repository_ctx.path(":install_manifest.json")` resolves.
    repository_ctx.file("install_manifest.json", "{}\n")

    # Sentinel marker that cc_toolchain_repo checks to detect an ungenerated
    # sysroot and degrade to a stub toolchain.
    repository_ctx.file(
        APTPREP_FAKE_SYSROOT_MARKER,
        "This sysroot/packages repo is an ungenerated aptprep stand-in.\n",
    )

aptprep_fake_repo = repository_rule(
    implementation = _aptprep_fake_repo_impl,
    attrs = {
        "repo_name": attr.string(mandatory = True),
    },
)
