# Generated by toolchains_repo.bzl
#
# These can be registered in the workspace file or passed to --extra_toolchains flag.
# By default all these toolchains are registered by the aptprep_register_toolchains macro
# so you don't normally need to interact with these targets.

# Declare a toolchain Bazel will select for running the tool in an action
# on the execution platform.
toolchain(
    name = "aptprep_toolchain",
    toolchain = "@%{USER_REPOSITORY_NAME}//:aptprep_toolchain",
    toolchain_type = "@@rules_aptprep+//aptprep:toolchain_type",
)

# Convenience alias to register all toolchains
alias(
    name = "all",
    actual = ":aptprep_toolchain",
    visibility = ["//visibility:public"],
)
