# Generated by the aptprep `cc_toolchain` repo rule (Unit D). Do not edit.
#
# This BUILD is intentionally tiny: all reusable logic lives in the checked-in
# `aptprep_cc_toolchain(...)` macro and the `cc_toolchain_config` rule. The repo
# rule (cc_toolchain_repo.bzl) renders the wrapper scripts next to this file and
# fills in the fully-resolved exec-relative path strings below.

load("@rules_aptprep//aptprep/cc:defs.bzl", "aptprep_cc_toolchain")

package(default_visibility = ["//visibility:public"])

# Each per-tool wrapper rendered by the repo rule is exported so the macro can
# reference it both as a label (sandbox input via the §6.4 filegroups) and so its
# exec path resolves for the `tool_paths` strings the config rule consumes.
exports_files(glob(["wrappers/*.sh"]))

%{WRAPPER_FILEGROUPS}

aptprep_cc_toolchain(
    name = "%{NAME}",
    target_triple = "%{TARGET_TRIPLE}",
    target_arch = "%{TARGET_ARCH}",
    target_cpu = "%{TARGET_CPU}",
    target_os = "%{TARGET_OS}",
    compiler_sysroot_repo = "%{COMPILER_SYSROOT_REPO}",
    target_sysroot_repo = "%{TARGET_SYSROOT_REPO}",
    compiler_sysroot_path = "%{COMPILER_SYSROOT_PATH}",
    target_sysroot_path = "%{TARGET_SYSROOT_PATH}",
    clang_version = "%{CLANG_VERSION}",
    cxx_std = "%{CXX_STD}",
    cxx_builtin_include_directories = %{CXX_BUILTIN_INCLUDE_DIRECTORIES},
    extra_compile_flags = %{EXTRA_COMPILE_FLAGS},
    extra_link_flags = %{EXTRA_LINK_FLAGS},
    exec_constraints = %{EXEC_CONSTRAINTS},
    target_constraints = %{TARGET_CONSTRAINTS},
    wrappers = %{WRAPPERS},
    tool_paths = %{TOOL_PATHS},
)
