# Generated by aptprep/repositories.bzl
load("@rules_aptprep//aptprep:toolchain.bzl", "aptprep_toolchain")

aptprep_toolchain(
    name = "aptprep_toolchain",
    target_tool = select({
        "@bazel_tools//src/conditions:host_windows": "%{BINARY_NAME}.exe",
        "//conditions:default": "%{BINARY_NAME}",
    }),
)
